# Generated by Django 5.0.7 on 2025-04-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_search', '0003_propertysearchrequest_property_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertysearchrequest',
            old_name='user_id',
            new_name='user',
        ),
    ]
