# Generated by Django 5.0.7 on 2025-04-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertysearchrequest',
            old_name='min_total_floor',
            new_name='min_total_floors',
        ),
        migrations.RenameField(
            model_name='propertysearchrequest',
            old_name='repair_state_id',
            new_name='repair_state',
        ),
    ]
