# Generated by Django 5.0.7 on 2025-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_rename_infrastucture_property_infrastructure'),
        ('property_search', '0002_rename_min_total_floor_propertysearchrequest_min_total_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysearchrequest',
            name='property_category',
            field=models.ManyToManyField(related_name='search_property_category', to='property.propertycategory'),
        ),
    ]
