# Generated by Django 5.0.7 on 2025-04-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='living_ares',
            new_name='living_area',
        ),
    ]
