# Generated by Django 5.0.7 on 2025-04-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_rename_living_ares_property_living_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='infrastucture',
            new_name='infrastructure',
        ),
    ]
