# Generated by Django 5.0.7 on 2025-06-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_propertytype_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='transcription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='transcription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='district',
            name='transcription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='transcription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='repairstate',
            name='transcription',
            field=models.CharField(default='', max_length=100),
        ),
    ]
