# Generated by Django 5.0.7 on 2025-04-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
