# Generated by Django 5.0.7 on 2025-05-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='user_bot_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_bot_pass',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
