# Generated by Django 5.0.7 on 2025-05-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0003_baseuser_user_bot_id_baseuser_user_bot_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_role',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='common.userrole'),
        ),
    ]
