# Generated by Django 5.0.7 on 2025-06-14 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Тип материалов дома',
                'verbose_name_plural': 'Типы материалов дома',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Категория объекта недвижимости',
                'verbose_name_plural': 'Категории объектов недвижимости',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('transcription', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Тип объекта недвижимости',
                'verbose_name_plural': 'Типы объектов недвижимости',
            },
        ),
        migrations.CreateModel(
            name='RepairState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Состояние ремонта',
                'verbose_name_plural': 'Состояния ремонта',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='property.city')),
            ],
            options={
                'verbose_name': 'Район города',
                'verbose_name_plural': 'Районы города',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=200)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('living_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_count', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('total_floor', models.IntegerField()),
                ('has_balcony', models.BooleanField(default=0)),
                ('infrastructure', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=1)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_types', to='property.buildingtype')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='property.district')),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('property_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_categories', to='property.propertycategory')),
                ('property_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_types', to='property.propertytype')),
                ('repair_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_stetes', to='property.repairstate')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
    ]
