# Generated by Django 5.0.7 on 2025-06-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertycategory_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='transcription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='transcription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='district',
            name='transcription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='repairstate',
            name='transcription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='repairstate',
            name='description',
            field=models.TextField(),
        ),
    ]
